### PR TITLE
Add requirements.txt and Dockerfile. Issue 11 and 15

### PR DESCRIPTION
**Pull request by HWataru**
I created PR with commits for #11 and #16 together because Dockerfile depend on requirements.txt.

### CODE REVIEW

**Comment by rasshai** [comment]
Thanks. Could you also add Git installation in the Dockerfile? The user will need it anyway, so it might as well be included in the Dockerfile instead of making the user to install it manually.

**Comment by HWataru** [comment]
Is git required for running this project ?
If not git wouldn't be included in dockerfile.

I create dockerfile as execution environment not development environment.

**Comment by HWataru** [comment]
But it is needed to add a description how to use Dockerfile.
Once I will close this PR and split PR into two PRs.

**Comment by HWataru** [comment]
open #20 and #21

**Pull request closed without merging**
